name: Publish
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run clean
    - run: npm run build
    - run: npm run coverage

    - name: Create Coverage Badges
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        source: coverage/coverage-summary.json
        output: coverage/badges.svg

    # coverage 文件夹移动到build，方便 部署
    - run: cp -rp coverage build

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
        output: build/CONTRIBUTORS.svg

    - name: Npm Publish 
      uses: JS-DevTools/npm-publish@v1
      if: github.ref == 'refs/heads/master'
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./package.json    

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build    
